linters:
  enable:
    - copyloopvar
    - durationcheck
    - errcheck
    - forcetypeassert
    - godot
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usetesting
  # No presets configured; enable linters explicitly above
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
run:
  tests: true
  timeout: 5m
